name: Pylint and mypy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install mypy
        pip install pygame-ce
    - name: Analysing the code with pylint and mypy
      run: |
        pylint $(git ls-files '*.py')
        mypy main.py
