name: Pylint and mypy

on: [push]

jobs:
  build:
    runs-on: debian-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install mypy
    - name: Analysing the code with pylint and mypy
      run: |
        pylint $(git ls-files '*.py')
        mypy main.py
